# default settings, should be overwritten

TCEpage:
  author: 'StarOfCreation'
  author_email: info@starofcreation.ch
  author_phone: '+41790000000'
  org_name: 'StarOfCreation'
  org_logo: 'EXT:soc/Resources/Public/Images/starofcreation_journey_to_soul_logo.png'

# Das ist ein Test
